# 媒体配置（可选，如果你的文档中有图片或附件）
media:
  label: 资源
  input: public/docs
  output: public/docs
  categories: [ image, document ]

# 内容配置
content:
  - name: docs
    label: 文档
    type: collection
    path: contents/docs
    subfolders: false  # 允许子文件夹
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: noLink
        label: Hide Link
        type: boolean
        default: false
      - name: tag
        label: Tag
        type: string
      - name: order
        label: Order
        type: number
    view:
      fields: [ title, order, tag ]
      primary: title
      sort: [ order, title ]
      default:
        search: ''
        sort: order
      layout: tree  # 使用树形显示子文件夹
      node:
        filename: index.mdx
