media:
  label: 资源
  input: public/docs
  output: /docs
  categories: [ image, document ]

content:
  - name: docs
    label: 文档
    type: collection
    path: contents/docs
    subfolders: true
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: noLink
        label: Hide Link
        type: boolean
        default: false
      - name: tag
        label: Tag
        type: string
      - name: order
        label: Order
        type: number
    view:
      primary: title
      fields: [ title, order, tag ]
      sort: [ order ]
      layout: list    # 临时改为 list 便于排查
